# Generated by Django 3.1.13 on 2024-02-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20240213_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'SignUp'},
        ),
    ]
