# Generated by Django 3.1.13 on 2024-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20240213_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to=())),
            ],
            options={
                'verbose_name': 'Apartment',
            },
        ),
    ]
