# Generated by Django 3.1.13 on 2024-02-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_apartment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Apartments',
        ),
    ]
