# Generated by Django 3.1.13 on 2024-02-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20240214_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
