# Generated by Django 3.1.13 on 2024-02-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_private_classes_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_classes',
            name='img',
        ),
    ]
