# Generated by Django 3.1.13 on 2024-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_private_classes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_classes',
            name='img',
            field=models.ImageField(default='static/image/personalclass.png', upload_to=''),
        ),
    ]
