# Generated by Django 3.1.13 on 2024-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_private_classes_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
