# Generated by Django 3.1.13 on 2024-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_apartments_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_classes',
            name='departmentcourse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
