# Generated by Django 3.1.13 on 2024-02-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_private_classes_departmentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_classes',
            name='img',
        ),
    ]
