# Generated by Django 3.1.13 on 2024-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_private_classes_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCivilClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcourse', models.CharField(max_length=100, null=True)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateElectricClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcourse', models.CharField(max_length=100, null=True)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMechanicalClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcourse', models.CharField(max_length=100, null=True)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSoftwarClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcourse', models.CharField(max_length=100, null=True)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Private_Classes',
            new_name='PrivateChemicalClasses',
        ),
    ]
