# Generated by Django 3.1.13 on 2024-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_catigory_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
