# Generated by Django 3.1.13 on 2024-02-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_scholarship_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatigoryClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
        migrations.RemoveField(
            model_name='privatechemicalclasses',
            name='departmentcourse',
        ),
        migrations.RemoveField(
            model_name='privatecivilclasses',
            name='departmentcourse',
        ),
        migrations.RemoveField(
            model_name='privateelectricclasses',
            name='departmentcourse',
        ),
        migrations.RemoveField(
            model_name='privatemechanicalclasses',
            name='departmentcourse',
        ),
        migrations.RemoveField(
            model_name='privatesoftwarclasses',
            name='departmentcourse',
        ),
        migrations.AddField(
            model_name='privatechemicalclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privatecivilclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privateelectricclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privatemechanicalclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privatesoftwarclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
    ]
