# Generated by Django 3.1.13 on 2024-02-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20240220_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechemicalclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privatecivilclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privateelectricclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
        migrations.AddField(
            model_name='privatemechanicalclasses',
            name='departmentcours',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='pages.catigoryclasses'),
        ),
    ]
