# Generated by Django 3.1.13 on 2024-02-20 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20240220_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
