# Generated by Django 3.1.13 on 2024-02-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20240220_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
