# Generated by Django 3.1.13 on 2024-02-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20240220_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechemicalclasses',
            name='departmentcours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatecivilclasses',
            name='departmentcours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privateelectricclasses',
            name='departmentcours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatemechanicalclasses',
            name='departmentcours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatesoftwarclasses',
            name='departmentcours',
            field=models.CharField(max_length=100),
        ),
    ]
