# Generated by Django 3.1.13 on 2024-02-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20240220_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatigoryClasses',
        ),
    ]
