# Generated by Django 3.1.13 on 2024-02-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_catigoryclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateSoftwarClasses',
        ),
    ]
