# Generated by Django 3.1.13 on 2024-02-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_delete_privatesoftwarclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatigoryClasses',
        ),
    ]
