# Generated by Django 3.1.13 on 2024-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_delete_catigoryclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatigoryClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSoftwarClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcours', models.CharField(max_length=50)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
