# Generated by Django 3.1.13 on 2024-02-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20240220_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateSoftwarClasses',
        ),
    ]
