# Generated by Django 3.1.13 on 2024-02-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_privatesoftwarclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateSoftwarClasses',
        ),
    ]
