# Generated by Django 3.1.13 on 2024-02-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_privatesoftwarclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateSoftwarClasses',
        ),
    ]
