# Generated by Django 3.1.13 on 2024-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_delete_privatesoftwarclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentcours', models.CharField(choices=[('Softwar-Engineering', 'Softwar-Engineering'), ('Civil-Engineering', 'Civil-Engineering'), ('Chemical-Engineering', 'Chemical-Engineering'), ('Electric-Engineering', 'Electric-Engineering'), ('Mechanical-Engineering', 'Mechanical-Engineering')], max_length=200, null=True)),
                ('coursename', models.CharField(blank=True, max_length=50, null=True)),
                ('teachername', models.CharField(blank=True, max_length=50, null=True)),
                ('teacherphonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
