# Generated by Django 3.1.13 on 2024-02-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_privateclasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateChemicalClasses',
        ),
        migrations.DeleteModel(
            name='PrivateCivilClasses',
        ),
        migrations.DeleteModel(
            name='PrivateElectricClasses',
        ),
        migrations.DeleteModel(
            name='PrivateMechanicalClasses',
        ),
    ]
