# Generated by Django 5.0.2 on 2024-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_apartments_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
