# Generated by Django 5.0.2 on 2024-02-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_apartments_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='img',
        ),
    ]
