# Generated by Django 5.0.2 on 2024-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_remove_apartments_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
