from django.urls import path
from .import views


urlpatterns = [
    path('', views.masterpage,name='masterpage'),
     #path('SignUpAdmin.html',views.si,name='SignUpAdmin'),
     path('SignUpStudent.html',views.SignUpStudent,name='SignUpStudent'),
    path('SignUpUser.html',views.SignUpUser,name='SignUpUser'),
    path('ToSignUp.html',views.ToSignUp,name='ToSignUp'),
    path('choose.html',views.choose,name='choose'),
    path('apartmentsroom.html',views.apartmentsroom,name='apartmentsroom'),
    path('oneapartment.html',views.oneapartment,name='oneapartment'),
    path('privateclass.html',views.privateclass,name='privateclass'),
    path('departmentcourses.html',views.departmentcourses,name='departmentcourses'),
     path('showSoftwarclasses.html',views.showSoftwarclasses,name="showSoftwarclasses"),
    path('showchemicalclasses.html',views.showchemicalclasses,name="showchemicalclasses"),
    path('showmechanicalclasses.html',views.showmechanicalclasses,name="showmechanicalclasses"),
    path('showelectricclasses.html',views.showelectricclasses,name="showelectricclasses"),
    path('showcivilclasses.html',views.showcivilclasses,name="showcivilclasses"),
    path('addclasses.html',views.addclasses,name='addclasses'),
    path('addsoftwarclasses.html',views.addsoftwarclasses,name="addsoftwarclasses"),
     path('addelectricclasses.html',views.addelectricclasses,name="addelectricclasses"),
     path('addcivilclasses.html',views.addcivilclasses,name="addcivilclasses"),
     path('addchemicalclasses.html',views.addchemicalclasses,name="addchemicalclasses"),
        path('addmechanicalclasses.html',views.addmechanicalclasses,name="addmechanicalclasses"),
         path('addscholarship.html',views.addscholarship,name="addscholarship"),
    path('forstudentsusers.html',views.forstudentsusers,name='forstudentsusers'),
    path('forusers.html',views.forusers,name='forusers'),
    path('ADDING.html',views.ADDING,name='ADDING'),
    path('addapartment.html',views.addapartment,name='addapartment'),
    path('showscholarships.html',views.showscholarships,name='showscholarships'),
    path('scholarshipswith.html',views.scholarshipswith,name='scholarshipswith'),
    path('scholarshipswithout.html',views.scholarshipswithout,name='scholarshipswithout'),
     path('searchingapartments.html',views.searchingapartments,name='searchingapartments'),
     path('apartmentsprice.html',views.apartmentsprice,name='apartmentsprice'),
      path('apartmentsroom.html',views.apartmentsroom,name='apartmentsroom'),
       path('Loginstudent.html',views.Loginstudent,name='Loginstudent'),
        path('Loginuser.html',views.Loginuser,name='Loginuser'),
       path('aboutus.html',views.aboutus,name="aboutus"),
       path('apartmentarea.html',views.apartmentarea,name='apartmentarea'),
       path('More.html',views.More,name='More'),
       path('Loginadmin.html',views.Logiadmin,name='Loginadmin'),
       path('adminapartments.html',views.adminapartments,name='adminapartments'),
       path('adminusers.html',views.adminusers,name='adminusers'),
       path('adminsoftwar.html',views.adminsoftwar,name='adminsoftwar'),
        path('admincivil.html',views.admincivil,name='admincivil'),
        path('adminchemical.html',views.adminchemical,name='adminchemical'),
         path('adminelectrical.html',views.adminelectrical,name='adminelectrical'),
          path('adminmechanical.html',views.adminmechanical,name='adminmechanical'),
            path('adminscholarship.html',views.adminscholarship,name='adminscholarship'),
            path('privateclassestables.html',views.privateclassestables,name='privateclassestables'),
            path('wichtable.html',views.wichtable,name='wichtable'),
             path('foradmin.html',views.foradmin,name='foradmin'),
             path('updateapartment.html/<str:pk>',views.updateapartment,name='updateapartment'),
             path('updatescholarship.html/<str:pk>',views.updatescholarship,name='updatescholarship'),
             path('updatesoftwar.html/<str:pk>',views.updatesoftwar,name='updatesoftwar'),
             path('updatecivil.html/<str:pk>',views.updatecivil,name='updatecivil'),
             path('updateelectric.html/<str:pk>',views.updateelectric,name='updateelectric'),
             path('updatechemical.html/<str:pk>',views.updatechemical,name='updatechemical'),
              path('updatemechanical.html/<str:pk>',views.updatemechanical,name='updatemechanical'),
             path('wichuser.html',views.wichuser,name='wichuser'),
             path('wichlogin.html',views.wichlogin,name='wichlogin'),
             path('signorlog.html',views.signorlog,name='signorlog'),
             path('home.html',views.home,name='home'),




    
] 

